### ISSUE TITLE
twit not in package.json

### ISSUE THREAD

**Issue by saiichihashimoto** [marcoajonker/poptags#5]
```
rm -rf node_modules
npm install
npm start
```

Gives you this error:

```
Error: Cannot find module 'twit'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/saiichi/Workspace/poptags/routes/twitter.js:2:16
    at Object.<anonymous> (/Users/saiichi/Workspace/poptags/routes/twitter.js:24:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by saiichihashimoto** [comment]
Don't be closin things you haven't pushed yet, yo.
